#!/bin/bash
# =============================================================================
# Setup Script for Audit Log Service
# =============================================================================

set -e

echo "🚀 Setting up Audit Log Service..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
check_prereqs() {
    echo "📋 Checking prerequisites..."
    
    if ! command -v docker &> /dev/null; then
        echo -e "${RED}❌ Docker is not installed${NC}"
        exit 1
    fi
    
    if ! command -v docker-compose &> /dev/null; then
        echo -e "${RED}❌ Docker Compose is not installed${NC}"
        exit 1
    fi
    
    if ! command -v openssl &> /dev/null; then
        echo -e "${RED}❌ OpenSSL is not installed${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✅ All prerequisites met${NC}"
}

# Create directories
create_dirs() {
    echo "📁 Creating directories..."
    mkdir -p certs keys nginx/conf.d monitoring/rules monitoring/grafana/provisioning/datasources monitoring/grafana/provisioning/dashboards monitoring/grafana/dashboards sql
    echo -e "${GREEN}✅ Directories created${NC}"
}

# Generate certificates
generate_certs() {
    echo "🔐 Generating certificates..."
    
    if [ -f "certs/ca.crt" ]; then
        echo -e "${YELLOW}⚠️  Certificates already exist, skipping...${NC}"
        return
    fi
    
    # Generate CA
    openssl genrsa -out certs/ca.key 4096
    openssl req -new -x509 -days 3650 -key certs/ca.key -out certs/ca.crt \
        -subj "/CN=Audit Log CA/O=Audit Log Service"
    
    # Generate server certificate
    openssl genrsa -out certs/server.key 2048
    openssl req -new -key certs/server.key -out certs/server.csr \
        -subj "/CN=localhost/O=Audit Log Service"
    openssl x509 -req -days 365 -in certs/server.csr \
        -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial \
        -out certs/server.crt
    
    # Generate sample client certificate
    openssl genrsa -out certs/client.key 2048
    openssl req -new -key certs/client.key -out certs/client.csr \
        -subj "/CN=sample-service/O=Audit Log Service"
    openssl x509 -req -days 365 -in certs/client.csr \
        -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial \
        -out certs/client.crt
    
    # Generate master key
    openssl rand -base64 32 > keys/master.key
    
    # Set permissions
    chmod 600 certs/*.key keys/master.key
    
    echo -e "${GREEN}✅ Certificates generated${NC}"
}

# Create environment file
create_env() {
    echo "⚙️  Creating environment file..."
    
    if [ -f ".env" ]; then
        echo -e "${YELLOW}⚠️  .env file already exists, skipping...${NC}"
        return
    fi
    
    # Generate random passwords
    DB_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
    GRAFANA_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
    MEILI_KEY=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
    
    cat > .env << EOF
# Generated by setup.sh on $(date)

# Database
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://audit_user:\${DB_PASSWORD}@postgres:5432/audit_db

# Application
DEBUG=false
LOG_LEVEL=INFO

# Monitoring
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}

# Meilisearch (optional)
MEILISEARCH_API_KEY=${MEILI_KEY}
EOF
    
    chmod 600 .env
    
    echo -e "${GREEN}✅ Environment file created${NC}"
    echo -e "${YELLOW}⚠️  Please review .env and update as needed${NC}"
}

# Start services
start_services() {
    echo "🐳 Starting Docker services..."
    
    docker-compose up -d postgres
    
    echo "⏳ Waiting for PostgreSQL to be ready..."
    sleep 10
    
    docker-compose up -d
    
    echo -e "${GREEN}✅ Services started${NC}"
}

# Show status
show_status() {
    echo ""
    echo "📊 Service Status:"
    echo "=================="
    docker-compose ps
    
    echo ""
    echo "🔗 Access URLs:"
    echo "==============="
    echo "  API:        http://localhost:8000"
    echo "  API Docs:   http://localhost:8000/docs (if DEBUG=true)"
    echo "  Health:     http://localhost:8000/health"
    echo "  Prometheus: http://localhost:9090"
    echo "  Grafana:    http://localhost:3000"
    
    echo ""
    echo "📝 Quick Commands:"
    echo "=================="
    echo "  View logs:     docker-compose logs -f api"
    echo "  Stop all:      docker-compose down"
    echo "  Restart API:   docker-compose restart api"
}

# Main
main() {
    echo "=========================================="
    echo "   Audit Log Service Setup"
    echo "=========================================="
    echo ""
    
    check_prereqs
    create_dirs
    generate_certs
    create_env
    
    read -p "Start services now? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        start_services
        show_status
    else
        echo ""
        echo "To start services later, run:"
        echo "  docker-compose up -d"
    fi
    
    echo ""
    echo -e "${GREEN}✅ Setup complete!${NC}"
}

main "$@"
